---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD | quote }}
  MONGO_APP_DATABASE: {{ .Values.mongodb.env.MONGO_APP_DATABASE | quote }}
  MONGO_APP_USERNAME: {{ .Values.mongodb.env.MONGO_APP_USERNAME | quote }}
  MONGO_APP_PASSWORD: {{ .Values.mongodb.env.MONGO_APP_PASSWORD | quote }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image | quote }}
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: mongodb-secret
        ports:
        - containerPort: {{ .Values.mongodb.containerPort }}
        resources:
{{- toYaml .Values.mongodb.resources | nindent 10 }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.mongodb.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
spec:
  ports:
  - port: {{ .Values.mongodb.containerPort }}
    targetPort: {{ .Values.mongodb.containerPort }}
  selector:
    app: mongodb
  clusterIP: None
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init-reports-user-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongodb-init-reports-user
          image: {{ .Values.mongodb.image | quote }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: mongodb-secret
          resources:
{{- toYaml .Values.mongodb.resources | nindent 12 }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              until mongosh "mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongodb:27017/admin" --eval "db.adminCommand('ping')" >/dev/null 2>&1; do
                sleep 5
              done
              mongosh "mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongodb:27017/admin" --eval "db = db.getSiblingDB('$MONGO_APP_DATABASE'); if (db.getUser('$MONGO_APP_USERNAME') == null) { db.createUser({ user: '$MONGO_APP_USERNAME', pwd: '$MONGO_APP_PASSWORD', roles: [{ role: 'readWrite', db: '$MONGO_APP_DATABASE' }] }); }"
